networks:
  management:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.254

  transit:
    driver: bridge
    ipam:
      config:
        - subnet: 10.255.0.0/29
          gateway: 10.255.0.6

  malmo:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.254

  london:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.1.0/24
          gateway: 10.20.1.254
