frr version 10.1
frr defaults traditional
hostname edge-london
service integrated-vtysh-config
log stdout

interface eth0
 description management

interface eth1
 description transit-to-malmo
 ip address 10.255.0.2/30
 ip ospf area 0.0.0.0

interface eth2
 description london-site-network
 ip address 10.20.1.1/24
 ip ospf area 0.0.0.0

router bgp 65002
 bgp router-id 10.255.0.2
 no bgp ebgp-requires-policy
 neighbor 10.255.0.1 remote-as 65001
 network 10.20.1.0/24

router ospf
 ospf router-id 10.255.0.2
 network 10.255.0.0/30 area 0.0.0.0
 network 10.20.1.0/24 area 0.0.0.0

line vty
