frr version 10.1
frr defaults traditional
hostname edge-malmo
service integrated-vtysh-config
log stdout

router bgp 65001
 bgp router-id 10.255.0.1
 no bgp ebgp-requires-policy
 neighbor 10.255.0.2 remote-as 65002
 network 10.10.1.0/24

router ospf
 ospf router-id 10.255.0.1
 network 10.255.0.0/29 area 0.0.0.0
 network 10.10.1.0/24 area 0.0.0.0

line vty
